name: Deploy
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install
        run: npm ci
      # - name: Lint
      #   run: npm run lint
      - name: Test
        run: npm run test
      - name: Deploy
        run: echo "Deploying ${{ github.repository }}..."
