name: Issue
on: issues
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Event Details
        run: echo ${{ toJSON(github.event) }}
      - name: Issue Event
        run: echo ${{ toJSON(github.event.issue) }}
      - name: GitHub Context
        run: echo ${{ toJSON(github) }}
